### ISSUE TITLE
Texture Pack?

### ISSUE THREAD

**Issue by HappyGingerWolf** [Maxwelllondon92/RedSands#1]
Hey, I really love this mod, but I was wondering if you could make a texture pack version so it works with other maps? If you don't wanna do that, I could make it for you and credit you, if you'd let me. :)

**Comment by Maxwelllondon92** [comment]
If you want to is ok.
Let me know if you need any help for new textures or stuff ;)

Il Mar 3 Mar 2020, 14:13 HappyGingerWolf <notifications@github.com> ha
scritto:

**Comment by HappyGingerWolf** [comment]
I made the pack, but unfortunately it seems that overwriting existing tiles doesn't work very well, so it looks bad. I'll keep it around in case anuke ever fixes it, but it's doubtful.
The link is HappyGingerWolf/Red-Sands-Texture-Pack
